[versions]
scala-version = "3.2.1"
scalatest-version = "3.2.15"
spotless-version = "6.14.0"
scalafmt-version = "3.7.1"
# insert the versions of the dependencies here...

[libraries]
scala = { module = "org.scala-lang:scala3-library_3", version.ref = "scala-version" }
scalatest = { module = "org.scalatest:scalatest_3", version.ref = "scalatest-version" }
scalafmt-cli = { module = "org.scalameta:scalafmt-cli_2.13", version.ref = "scalafmt-version" }
scalafmt-config = { module = "org.scalameta:scalafmt-config_2.13", version.ref = "scalafmt-version" }
# insert the dependencies here...

[bundles]
scalafmt = [ "scalafmt-cli", "scalafmt-config" ]
# insert groups of dependencies here...

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless-version" }
# insert groups of dependencies here...