[versions]
scala-version = "3.2.1"
scalatest-version = "3.2.15"
spotless-version = "6.15.0"
scalafmt-version = "3.7.1"
wartremover-version = "3.0.9"
kotlin-qa-version = "0.34.1"
vertx-version = "4.3.7"
scalafx-version = "16.0.0-R24"
javafx-version = "16"
tuprolog-version = "4.1.1"
# insert the versions of the dependencies here...

[libraries]
scala = { module = "org.scala-lang:scala3-library_3", version.ref = "scala-version" }
scalatest = { module = "org.scalatest:scalatest_3", version.ref = "scalatest-version" }
scalafmt-cli = { module = "org.scalameta:scalafmt-cli_2.13", version.ref = "scalafmt-version" }
scalafmt-config = { module = "org.scalameta:scalafmt-config_2.13", version.ref = "scalafmt-version" }
wartremover = { module = "org.wartremover:wartremover_3.2.2", version.ref = "wartremover-version" }
vertx = { module = "io.vertx:vertx-core", version.ref = "vertx-version" }
scalafx = { module = "org.scalafx:scalafx_3", version.ref = "scalafx-version" }
javafx-base = { module = "org.openjfx:javafx-base", version.ref = "javafx-version" }
javafx-controls = { module = "org.openjfx:javafx-controls", version.ref = "javafx-version" }
javafx-fxml = { module = "org.openjfx:javafx-fxml", version.ref = "javafx-version" }
javafx-graphics = { module = "org.openjfx:javafx-graphics", version.ref = "javafx-version" }
javafx-media = { module = "org.openjfx:javafx-media", version.ref = "javafx-version" }
javafx-swing = { module = "org.openjfx:javafx-swing", version.ref = "javafx-version" }
javafx-web = { module = "org.openjfx:javafx-web", version.ref = "javafx-version" }
tuprolog = { module = "it.unibo.alice.tuprolog:2p-core", version.ref = "tuprolog-version" }
# insert the dependencies here...

[bundles]
scalafmt = [ "scalafmt-cli", "scalafmt-config" ]
javafx = [ "javafx-base", "javafx-controls", "javafx-fxml", "javafx-graphics", "javafx-media", "javafx-swing", "javafx-web" ]
# insert groups of dependencies here...

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless-version" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version.ref = "kotlin-qa-version" }
# insert groups of dependencies here...